# Generated by Django 3.2.18 on 2023-08-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(default='', max_length=11)),
                ('dsg', models.CharField(max_length=20)),
                ('salary', models.CharField(max_length=20)),
                ('city', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=20, null=True)),
            ],
        ),
    ]
